### ISSUE TITLE
Why was Python 3.5 dropped in 4.3.0?

### ISSUE THREAD

**Issue by Lauszus** [MrMinimal64/timezonefinder#100]
Thanks for an excellent library! I was just wondering why Python 3.5 is no longer supported since version 4.3.0?

**Comment by Lauszus** [comment]
The problem is that the wheel is named `timezonefinder-4.3.1-py3-none-any.whl`, thus it will try to install it on a device running Python 3.5 even though it will fail with the following error message:

```bash
ERROR: Package 'timezonefinder' requires a different Python: 3.5.3 not in '>=3.6'
```

I believe you have to make 3 copies of the wheel and name them: `timezonefinder-4.3.1-py36-none-any.whl`, `timezonefinder-4.3.1-py37-none-any.whl` and `timezonefinder-4.3.1-py38-none-any.whl`. If support for Python 3.5 really is dropped on purpose.

Please see: https://www.python.org/dev/peps/pep-0491/#file-name-convention

**Comment by MrMinimal64** [comment]
Thanks, also for pointing this out! 

That is, because I started using f'' format strings and numpy is soon also dropping the support for python 3.5:
https://numpy.org/doc/stable/release/1.18.0-notes.html

Even though the [PEP 491 FAQs](https://www.python.org/dev/peps/pep-0425/#id16) say: 

> [...] it may still use the py3-none-any tag [...] 

the version tags for the specific versions are now included in the wheels. Please check and reopen if the issue remains.

**Comment by Lauszus** [comment]
@MrMinimal64 thanks for fixing it so quickly! I have a bunch of shipped devices that failed to update due to pip failing to install your package.

**Comment by MrMinimal64** [comment]
you are welcome! may I ask in what context you are using the package?

**Comment by Lauszus** [comment]
@MrMinimal64 it's used for the time shown in UI for the following boat: https://candelaspeedboat.com/ :)

**Comment by MrMinimal64** [comment]
cool, keep up the good work! glad I could help.

**Comment by Lauszus** [comment]
@MrMinimal64 I was wondering how much difference the timezone data including ocean would make? For now since it's not an offshore boat I do not expect it to make any difference.

**Comment by MrMinimal64** [comment]
This is the data in use: https://github.com/evansiroky/timezone-boundary-builder
I am planning to make timezonefinder modular and offer both data versions in the future (v5.0, #87, #88, #89). I am not sure though when this is going to get released.

**Comment by Lauszus** [comment]
Yeah I saw that. Unfortunately it is not that easy for me to update to a newer version of Python in the boats that has already been shipped.

**Comment by Lauszus** [comment]
Yeah I saw that. Unfortunately it is not that easy for me to update to a newer version of Python in the boats, as I will have to do that manually for all of them then.

**Comment by MrMinimal64** [comment]
I think when you create your own fork and remove all f'' format strings the code should run under py3.5 
Then you could also manually parse the ocean data yourself.
I am sorry about the inconvenience.

**Comment by Lauszus** [comment]
No problem. For now I will just stick with 4.2.0, as do not think there will be any practical difference, as people will stay close to the shore. 

I will just use version 5 when we make a bigger boat :)

**Comment by MrMinimal64** [comment]
Ok. Be careful though, as the timezone data does change slightly from time to time.
Let me know when your big flying bot is ready, then I will work hard to release v5.0 :)
Greetings to beautiful Stockholm!

**Comment by Lauszus** [comment]
It's not used for anything critical. For now just a clock shown in "admin" mode in the UI. 

Haha I'll ping you when the boat is ready and the only thing left is using timezonefinder v5.0 :)

**Comment by Lauszus** [comment]
@MrMinimal64 btw it turned out it that the issue was due to a problem with piwheels: https://github.com/piwheels/piwheels/issues/208. 

I got him to remove the wheels from piwheels https://github.com/piwheels/packages/issues/109, as they were just duplicates of the ones on pypi and pypi implements the `data-requires-python` attribute, so it seems like it was only an issue for Raspberry Pi users.
