### ISSUE TITLE
Import error in converter.py

### ISSUE THREAD

**Issue by zedrdave** [MrMinimal64/timezonefinder#101]
I think there's an error in the latest version of the code that makes the `file_converter.py` script fail:

```
import path_modification  # to make timezonefinder package discoverable
```

should be:

```
from timezonefinder import path_modification  # to make timezonefinder package discoverable
```

**Comment by MrMinimal64** [comment]
The script is working for me. Can you please specify your error? How are you calling the script?

**Comment by MrMinimal64** [comment]
This should be fixed in v4.4.0

@zedrdave could you please try and confirm here if the issue has been fixed (so I can close this issue)?
There also is a new shell script ``parse_data.sh`` for automatically parsing ocean data.
Could you please try the new functionality and report back preferably directly in the respective issue #88? Thanks in advance.

**Comment by zedrdave** [comment]
Thanks for the fix! I will give it a try as soon as possible and report back (hopefully within a day or two).

**Comment by zedrdave** [comment]
Hello again!
Sorry for the delay! I was able to check and confirm that the convert_file script now works fine.

The `parse_data.sh` also does (although it fails if the `$WORKING_FOLDER_NAME` dir hasn't been created beforehand: perhaps better to use `/tmp/` and/or provide an option to set it through a script argument?).

Now that there is `parse_data.sh`, it might not be very difficult to add an option-based post-install script, that downloads and sets-up tzf with Ocean data, directly from pip/pipenv… If you are open to it, I'd be happy to look into that…

**Comment by MrMinimal64** [comment]
thanks for the feedback!

> Now that there is parse_data.sh, it might not be very difficult to add an option-based post-install script, that downloads and sets-up tzf with Ocean data, directly from pip/pipenv… If you are open to it, I'd be happy to look into that…

yes, that would be really great! please report your progress in issue #88

**Comment by jayvdb** [comment]
There is still `import path_modification` in https://github.com/MrMinimal64/timezonefinder/blob/663b340/timezonefinder/file_converter.py

**Comment by MrMinimal64** [comment]
Is there a problem with that?

**Comment by jayvdb** [comment]
Same bug as above.
It is invalid syntax on Python 3.

**Comment by MrMinimal64** [comment]
Can you please post the error you get?
This import is required in some configurations in order to make the parent package (`timezonefinder`) discoverable.
I can run the script with Python3.7 .
Please make sure to update to the latest version of timezonefinder.
