### ISSUE TITLE
Changes in time zones in a given location?

### ISSUE THREAD

**Issue by SultanOrazbayev** [MrMinimal64/timezonefinder#103]
There is a small number of locations that change time zone boundaries over time. Is there a way to get timezone offset at a given point in time for such locations?

**Comment by MrMinimal64** [comment]
You want to obtain the timezone a location had in the past? This is unfortunately not natively supported by this package. You could theoretically parse different versions of the [timezone data](https://github.com/evansiroky/timezone-boundary-builder/releases) and look up the timezone of the different "points in time". If you know the locations you are interested in advance (fixed) however, I guess the change of timezones of those locations can be figured out directly in a more convenient way (should be documented "officially" somewhere). Hope I could help.

**Comment by SultanOrazbayev** [comment]
Thank you for the quick feedback! Yes, I am trying to figure the timezone offset of a fixed location in the past, and I think `dateutil` might give that: https://dateutil.readthedocs.io/en/stable/_modules/dateutil/tz/tz.html

This would only work if timezone label (which I can get with your package) is persistent over time, so this might not work for some locations (e.g. Russia).
