### ISSUE TITLE
Result under multiprocessing is flaky

### ISSUE THREAD

**Issue by xwk** [MrMinimal64/timezonefinder#104]
I found the result returned by the timezone_at method is flaky when running under multiprocessing environment. By flaky, I mean it will return different results from one run to another. I have stripped down my code to following test case to help you reproduce the problem. 

```
import multiprocessing
from timezonefinder import TimezoneFinder

lat_lngs = [
    (-39.88267, 6.58189),
    (-41.68253, 2.39381),
    (-41.59774, 1.59106),
    (-39.75798, 0.58502),
    (-40.3352, 0.73756),
    (-41.7354, 7.75914),
    (-41.42347, 1.64142),
    (-43.66458, 9.14061),
    (-39.50622, 3.43441),
]

tf = TimezoneFinder()

def get_timezone_one(row):
    lat, lng = row
    return tf.timezone_at(lat=lat, lng=lng)

def run(lat_lngs):
    pool = multiprocessing.Pool(processes=2)
    return pool.map(get_timezone_one, lat_lngs)

def test_timezonefinder(assert_df_equal, test_data_folder):
    for i in range(50):
        res1 = run(lat_lngs)
        res2 = run(lat_lngs)
        assert res1 == res2

```
Just use pytest to run the test case. It will have high probablity to fail. More specifically, most of the time, the run() function will return [None, None, None, None, None, None, None, None, None], but sometimes it will return [None, None, None, None, None, None, None, None, 'Africa/Ndjamena'] or other different values.

My environment:
* Ubuntu 18.04
* Python 3.7.3
*  timezonefinder=4.4.0
* numba==0.49.1.  I had suspected whether it is caused by numba, but after removing the numba pkg from my python environment the problem persits.

**Comment by MrMinimal64** [comment]
Interesting. This behavior is unexpected, since the code should be deterministic. I will look into it as soon as possible. Thanks for pointing this out.

**Comment by MrMinimal64** [comment]
I guess multiprocessing.Pool does require the code to be thread safe, but parallel timezone queries (with a single TimezoneFinder instance) are not thread safe.
This is because a single TimezoneFinder instance keeps binary files open to consequtively read from them.
In order to achieve correct parallelism please create separate TimezoneFinder instances for every process.
Please reopen this issue if this is not the solution to the problem.
