### ISSUE TITLE
Support timezones in Antarctica

### ISSUE THREAD

**Issue by MrMinimal64** [MrMinimal64/timezonefinder#11]
May not be that important.

**Comment by goosey** [comment]
I would actually love support for timezones in Antarctica, but it's not actively breaking anything of ours (wherever it's critical, we're just replacing "uninhabited" with UTC). Would be nice though!

**Comment by MrMinimal64** [comment]
I am trying not to manually modify the underlying data set. I also don't really understand and like the timezone "uninhabited" (thats not just antarctica), but since very few people are probably interested in the timezone there (hence the name "uninhabited") I considered it not being that important and closed the issue. Feel free to work on this and add a pull request, though.

**Comment by evansiroky** [comment]
@goosey I'm the maintainer of https://github.com/evansiroky/timezone-boundary-builder/ which creates the underlying geodata.  My project currently doesn't have any Antarctica timezones, so if you want to start an issue over there proposing how to create the zones, that would be awesome.

**Comment by goosey** [comment]
@MrMinimal64 @evansiroky great, thanks! hopefully I'll find some time to do that
