### ISSUE TITLE
Loading Error 

### ISSUE THREAD

**Issue by jrifai** [MrMinimal64/timezonefinder#33]
Hi MrMinimal64,

Thank you for your library, it seems perfect for my project ! Indeed I have to convert many local times to UTC times from latitude and longitude features.

That's why I installed your project.
However I can't load your code. When I write:

`from timezonefinder import TimezoneFinder`

I have the following output:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-ffb6df41970c> in <module>()
----> 1 from timezonefinder import TimezoneFinder

/home/ecoast/anaconda2/lib/python2.7/site-packages/timezonefinder/__init__.py in <module>()
      1 from __future__ import absolute_import, division, print_function, unicode_literals
      2 
----> 3 from .timezonefinder import TimezoneFinder
      4 
      5 __version__ = '1.5.4'

/home/ecoast/anaconda2/lib/python2.7/site-packages/timezonefinder/timezonefinder.py in <module>()
     15 
     16 if numba is not None:
---> 17     from .helpers_numba import coord2int, distance_to_polygon, inside_polygon
     18 else:
     19     from .helpers import coord2int, distance_to_polygon, inside_polygon

/home/ecoast/anaconda2/lib/python2.7/site-packages/timezonefinder/helpers_numba.py in <module>()
      6 
      7 
----> 8 @jit('uint(i4,i4,i4,i4,i4,i4)', nopython=True, cache=True)
      9 def position_to_line(x, y, x1, x2, y1, y2):
     10     """tests if a point pX(x,y) is Left|On|Right of an infinite line from p1 to p2
could
/home/ecoast/anaconda2/lib/python2.7/site-packages/numba/decorators.py in jit(signature_or_function, locals, target, cache, **options)
    146 
    147     wrapper = _jit(sigs, locals=locals, target=target, cache=cache,
--> 148                    targetoptions=options)
    149     if pyfunc is not None:
    150         return wrapper(pyfunc)

/home/ecoast/anaconda2/lib/python2.7/site-packages/numba/decorators.py in wrapper(func)
    162         if config.DISABLE_JIT and not target == 'npyufunc':
    163             return _DisableJitWrapper(func)
--> 164         disp = dispatcher(py_func=func, locals=locals,
    165                           targetoptions=targetoptions,
    166                           **dispatcher_args)

/home/ecoast/anaconda2/lib/python2.7/site-packages/numba/dispatcher.py in __init__(self, py_func, locals, targetoptions, impl_kind)
    380         locals: dict, optional
    381             Mapping of local variable names to Numba types.  Used to override
--> 382             the types deduced by the type inference engine.
    383         targetoptions: dict, optional
    384             Target-specific config options.

/home/ecoast/anaconda2/lib/python2.7/site-packages/funcsigs/__init__.pyc in signature(obj)
     57 
     58     if not callable(obj):
---> 59         raise TypeError('{0!r} is not a callable object'.format(obj))
     60 
     61     if isinstance(obj, types.MethodType):

TypeError: u'uint(i4,i4,i4,i4,i4,i4)' is not a callable object
```

And yet I checked all requirements and if my libraries were updated.
If you can help me I will be very grateful to you !

**Comment by MrMinimal64** [comment]
hey jrifai,
at the first glance it looks like the error is related to Numba and its use.
I am not really sure what it is yet, but since you are the first one reporting that error, i guess it has something to do with dependencies...
Sorry for asking this, but have you installed the LLVM compiler?
http://numba.pydata.org/numba-doc/0.26.0/developer/contributing.html#buildenv
I will look further into it when you have.
Greetings

**Comment by jrifai** [comment]
Thanks for your answer.
I installed Numba with conda. Is not enough ?
I tried to install LLVM compiler, but no success for : `from timezonefinder import TimezoneFinder`

**Comment by MrMinimal64** [comment]
I don't know what the problem exaclty is, but i am pretty sure it is a problem with your Numba installation.
Please try uninstalling Numba and then check if timezonefinder works (without numba).
Then install numpy.
Then install llvmlite manually: http://llvmlite.pydata.org/en/latest/install/index.html#building-manually
and reinstall Numba (without conda).
That worked for me.
Hope that helped, but if not please consider looking for similar errors reported by Numba users.

**Comment by MrMinimal64** [comment]
Is your problem fixed?

**Comment by jrifai** [comment]
Hi,
Finally I used an other way to achieve my goal.
Thanks anyway for your avaibility !

**Comment by timothyb0912** [comment]
Hi, I wanted to second the fact that I am experiencing this issue as well. I am using a Mac OS X El Capitan version 10.11.4

Like MrMinimal64, I installed Numba using conda install Numba before pip installing timezonefinder.
I was unable to import timezonefinder with our without Numba
As for the LLVM compiler, it was already installed.

My terminal output from running "brew info llvm" is:
```
brew info llvm
llvm: stable 3.6.2 (bottled), HEAD [keg-only]
Next-gen compiler infrastructure
http://llvm.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb
==> Dependencies
Build: xz ✘, cmake ✘
==> Options
--universal
	Build a universal binary
--with-clang
	Build the Clang compiler and support libraries
--with-clang-extra-tools
	Build extra tools for Clang
--with-compiler-rt
	Build Clang runtime support libraries for code sanitizers, builtins, and profiling
--with-libcxx
	Build the libc++ standard library
--with-lld
	Build LLD linker
--with-lldb
	Build LLDB debugger
--with-python
	Build Python bindings against Homebrew Python
--with-rtti
	Build with C++ RTTI
--with-utils
	Install utility binaries
--HEAD
	Install HEAD version
==> Caveats
LLVM executables are installed in /usr/local/opt/llvm/bin.
Extra tools are installed in /usr/local/opt/llvm/share/llvm.

This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.
```
If there is anything that you think I'm doing incorrectly, pointers would be greatly appreciated!

**Comment by MrMinimal64** [comment]
First of all, thanks for reporting.
Since I don't know how @jrifai solved the issue after all and I do not know too much about Numba or llvm, I can basically just give you the same advice:

Consider if it is really necessary for you to use the package with Numba. If that's true:

> Please try uninstalling Numba completely (reverse your conda installation) and then check if timezonefinder works (without numba).
(install numpy)
Then install llvmlite manually: http://llvmlite.pydata.org/en/latest/install/index.html#building-manually
and reinstall Numba (I did it without conda).

On https://github.com/numba/numba it says the dependency is llvmlite so maybe your llvm version is not needed.

Please let me know if and how you solved the issue. Thanks

**Comment by timothyb0912** [comment]
@MrMinimal64: No problem.
I tried `conda uninstall numba` again, and timezonefinder magically worked. I'm not sure why it worked this time but not the first time I imported timezonefinder without Numba.

Thanks for pointing me in the right direction!

**Comment by MrMinimal64** [comment]
Ok, great. But could you please check if you are using Numba now:

> from timezonefinder import TimezoneFinder
print(TimezoneFinder.using_numba())

**Comment by timothyb0912** [comment]
I used the two commands you posted and got `False`.

**Comment by MrMinimal64** [comment]
So then that means, your timezonefinder works because you are not using it with numba. But you don't have you, it's just slower.
