### ISSUE TITLE
'uninhabited' returned error

### ISSUE THREAD

**Issue by ryan-mccaffrey** [MrMinimal64/timezonefinder#37]
Hi MrMinimal64,

I came across your timezonefinder and realized it would be perfect for my project, so I tried using it. I have been trying to use the timezone_at() method, but I receive an answer of 'uninhabited' for every location I put in.

To test this further, I tried using the geo-coordinates of New York, NY for timezone_at(), certain_timezone_at(), and closest_timezone_at(), and received a response of 'uninhabited' for all three. The response to my TimezoneFinder.using_numba() is False. My version of timezonefinder is 1.5.6

Any clues as to how fix this would be greatly appreciated. Thanks for the hard work on this library; it seems like it would be really great if it worked properly for me!

**Comment by MrMinimal64** [comment]
Hello Ryan,

please send me the Points (coordinates in latitude and longitude) you are testing.
My first guess is, that you switched latitude with longitude. The functions always take function(longitude, latitude) or to make sure simply function(lng=your_longitude,lat=your_latitude).

Greetings.

**Comment by ryan-mccaffrey** [comment]
Geez, I'm so clumsy. Works perfectly! Sorry for wasting your time haha

**Comment by adamchainz** [comment]
I think it's a bit of a problem with timezonefinder's API, since it's back-to-front from the de-facto lat-lng. This could be avoided from happening again by making it keyword-args-only. @MrMinimal64 what's your opinion on that?

**Comment by MrMinimal64** [comment]
Yes, you are right. For me it was straight forward to use (lng,lat) because in math I am used to (x,y), but I realized, that (lat,lng) is actually kind of the standard with coordinates...
The problems with keyword-only args are:
1. only supported by Python3 I believe
2. some peoples' code would break 
(still better than simply switching to lat,lng breaking their code that way however)

Maybe the best compromise would be to clarify it in the readme by also using keyword arguments there and point out this issue.
@adamchainz what do you think?

**Comment by cstich** [comment]
But is (lat, lng) really so much more popular than (lng, lat)? I have encountered both conventions sufficiently often that I am always confused and have to double check.

**Comment by MrMinimal64** [comment]
Maybe, but Adam is right: keyword-only args would actually prevent those confusions.
But I think this is not as important as supporting Python 2...

**Comment by adamchainz** [comment]
1. Keyword only args can be implemented on Python 2 with a decorator.
2. Not much

From my experience lat-lng is a little bit more popular but anyway keyword args only would solve this

**Comment by MrMinimal64** [comment]
Ok. Do you want to implement this, since it seems you have way more experience with this? :D

**Comment by adamchainz** [comment]
On it in #38
