### ISSUE TITLE
from timezonefinder import TimezoneFinder [type error]

### ISSUE THREAD

**Issue by VedAustin** [MrMinimal64/timezonefinder#41]
using `from timezonefinder import TimezoneFinder`. Returns a type error. Not sure if it is OS dependent? I am currently running a Win 8.1, python 2.7 (Anaconda dist)

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-187-ffb6df41970c> in <module>()
----> 1 from timezonefinder import TimezoneFinder

C:\Users\Shetty\Anaconda\lib\site-packages\timezonefinder\__init__.py in <module>()
      1 from __future__ import absolute_import, division, print_function, unicode_literals
      2 
----> 3 from .timezonefinder import TimezoneFinder
      4 
      5 __version__ = '1.5.6'

C:\Users\Shetty\Anaconda\lib\site-packages\timezonefinder\timezonefinder.py in <module>()
     15 
     16 if numba is not None:
---> 17     from .helpers_numba import coord2int, distance_to_polygon_exact, distance_to_polygon, inside_polygon, all_the_same
     18 else:
     19     from .helpers import coord2int, distance_to_polygon_exact, inside_polygon, all_the_same, distance_to_polygon

C:\Users\Shetty\Anaconda\lib\site-packages\timezonefinder\helpers_numba.py in <module>()
      6 
      7 
----> 8 @jit('i1(i4,i4,i4,i4,i4,i4)', nopython=True, cache=True)
      9 def position_to_line(x, y, x1, x2, y1, y2):
     10     """tests if a point pX(x,y) is Left|On|Right of an infinite line from p1 to p2

C:\Users\Shetty\Anaconda\lib\site-packages\numba\decorators.pyc in jit(signature_or_function, locals, target, cache, **options)
    147                    targetoptions=options)
    148     if pyfunc is not None:
--> 149         return wrapper(pyfunc)
    150     else:
    151         return wrapper

C:\Users\Shetty\Anaconda\lib\site-packages\numba\decorators.pyc in wrapper(func)
    161             return _DisableJitWrapper(func)
    162         disp = dispatcher(py_func=func, locals=locals,
--> 163                           targetoptions=targetoptions)
    164         if cache:
    165             disp.enable_caching()

C:\Users\Shetty\Anaconda\lib\site-packages\numba\dispatcher.pyc in __init__(self, py_func, locals, targetoptions)
    274         self.targetctx = self.targetdescr.target_context
    275 
--> 276         pysig = utils.pysignature(py_func)
    277         arg_count = len(pysig.parameters)
    278 

C:\Users\Shetty\Anaconda\lib\site-packages\funcsigs\__init__.pyc in signature(obj)
     57 
     58     if not callable(obj):
---> 59         raise TypeError('{0!r} is not a callable object'.format(obj))
     60 
     61     if isinstance(obj, types.MethodType):

TypeError: u'i1(i4,i4,i4,i4,i4,i4)' is not a callable object
```

**Comment by MrMinimal64** [comment]
My guess is that something is wrong with your Numba installation and or its dependencies  (in the Python 2.7 anaconda environment).

Others also encountered this, but no one told me yet what the problem actually was:
https://github.com/MrMinimal64/timezonefinder/issues/33

The only short term solution I know would be to use it without Numba for now (simply uninstall Numba in your anaconda environment), with python 3 or to double check your Numba installation and its dependencies (llvmlite... https://github.com/numba/numba).

Please consider, opening up an issue directly at https://github.com/numba/numba or just contacting someone of their developers.

Hope I could help. Please write it here if and how you resolved the issue. Thanks.

**Comment by MrMinimal64** [comment]
Is there anyone who is successfully using timezonefinder with Python2.7 and Numba (and maybe even Anaconda)?

**Comment by VedAustin** [comment]
I updated `numba` to the lastest version but it had no effect. So according to your advise I uninstalled `numba` and it seems to have worked. Thanks for the work around. But I was now wondering if it will now run slower? I am asking as I have to query ~12M coordinates.

**Comment by VedAustin** [comment]
Also out of curiosity what is the best way to query 12M coordinates. Using `.apply` will take forever. Do you have a vectorized implementation?

**Comment by MrMinimal64** [comment]
Do you have llvmlite installed and have you ever successfully used Numba in this environment?
Yes, depending on which function you call using it without Numba is significantly slower (factor 4, minimum)!
wow, 12M coordinates 0.0 
I calculated that on my system (one core) it would take approx. 10m with the fastest setup (Numba and timezone_at() ). In my tests it took 0.4s for 10k Points.
So I highly recommend to use Python3 with Numba in that case (or to fix your environment) and you may want to start multiple processes.
What do you mean by "vectorized implementation"?
Giving a function a vector of 12m coordinates doesn't really make sense to me... enlighten me. :)

**Comment by VedAustin** [comment]
Yes, I will switch over to Python 3 really soon. I cannot recall using Numba directly except perhaps if another package was implementing it. So it might have worked. I will reinstall Numba after I perform some analysis on the time zone.  Yes you are right, vectorized implementation does not make sense here. I was instead meaning to ask, how did you query 10K points? Did you have to call the function each time you queried a new coordinate?

**Comment by MrMinimal64** [comment]
Yes, you simply:

list_of_points = [ (lng1,lat1), (...), ...]
tf = Timezonefinder()
for lng, lat in list_of_points:
tf.timezone_at(lng=lng,lat=lat)

**Comment by VedAustin** [comment]
Got it. Thank you. Also thank you for the great library. I will open an issue with the Numba soonish.

**Comment by VedAustin** [comment]
So earlier I had uninstalled numba. After finishing my analysis, I reinstalled numba and again tried to see if reinstalling fixed anything and it apparently did. So it works for the following versions:
`numba:     0.27.0-np111py27_0`
`conda-env:  2.5.2-py27_0`

**Comment by MrMinimal64** [comment]
Great. Please run this for me:

> from timezonefinder import TimezoneFinder
> print(TimezoneFinder.using_numba())

**Comment by MrMinimal64** [comment]
timezonefinder should work now with numba and py27 (see #44).
