### ISSUE TITLE
Question: inclusion of simplified data prefered?

### ISSUE THREAD

**Issue by MrMinimal64** [MrMinimal64/timezonefinder#46]
I am currently working on a simple GUI for this package and while visualizing the actual timezone polygons used internally in a map, I realized that for the most use cases, I can think of, the data is unnecessarily complex (e.g. small detailed islands on coastlines...)

Unfortunately the GUI is not finished yet, so I cannot really show the exact level of detail, but hopefully my point is understandable. (the JSON of a polygon of one zone is usually more than 100KB big)

So my question is: 
 Are there any objections to (just?!) including simplified data (=geometries) starting with the next release? Simplification just means certain points would additionally be classified as "inside a zone", without reassigning points which originally belong to a different zone (<- less complex polygons). 
In general I am interested in what you use this package for.

Your answers would simply influence where and how I would upload the results. Thanks for your feedback.

**Comment by evansiroky** [comment]
I'm the maintainer of [node-geo-tz](https://github.com/evansiroky/node-geo-tz) and [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder).  I don't use your project but am also interested in others' use cases.  My 2 cents is any simplification of geometry will end up producing wrong results at various edge case coordinates.

**Comment by MrMinimal64** [comment]
To clarify: I am talking about simplifications that are not producing "wrong results". The question just is what are wrong results... Obviously it would always make a real difference if one is interested whether a point is NOT inside a polygon (not just returning the best guess but rather "None" if that point is outside of the exact timezone). I am however not sure if anybody uses this package in such a way.
