### ISSUE TITLE
timezonefinder can't be used as an embedded module

### ISSUE THREAD

**Issue by thehcma** [MrMinimal64/timezonefinder#47]
If instead of using the Python interpreter, `timezonefinder` is used embedded in CPython, an ImportError exception will occur, rendering it unusable:

`
File ".../lib/python2.7/site-packages/timezonefinder/__init__.py", line 3, in <module>
    from .timezonefinder import TimezoneFinder
File ".../lib/python2.7/site-packages/timezonefinder/timezonefinder.py", line 7, in <module>
    from sys import argv, exit
ImportError: cannot import name argv
`

This occurs because `sys.path` is not available to the embedded interpreter.

A simple fix to this would be to make the import a local one inside the block:

`if __name__ == '__main__':`

**Comment by MrMinimal64** [comment]
Thanks for the suggestion. Unfortunately I don't have any time to look into this right now. Can someone else please help out and send a Pull request?

**Comment by adamchainz** [comment]
I don't understand what is meant by "used embedded in CPython", and under what circumstances `sys.argv` isn't set.

Probably it's a simple change to change the module to `import sys` and only access `sys.argv` in the functiosn that need it, that's also the more idiomatic way of using `sys`.

**Comment by thehcma** [comment]
Embedded Python means the Python interpreter is not being used in the command-line, rather a piece of C/C++ code is invoking the interpreter via its C API.

In such cases, sys.argv is not initialized as you can see here:

https://docs.python.org/3/c-api/intro.html#embedding-python

And, yes, your comment about importing it where it is accessed is the way to go.

A PR to fix this is actually very simple, rather than doing a global import for sys, such an import should go into the block where the test:

if __name__ == "__main__"

is made

**Comment by thehcma** [comment]
I submitted a PR for this.
