### ISSUE TITLE
Get the Time Zone offset

### ISSUE THREAD

**Issue by communikein** [MrMinimal64/timezonefinder#51]
Is there a way to get the Time Zone GMT offset (-1, +14, 0, ...), instead of the Time Zone name?

**Comment by MrMinimal64** [comment]
You can extract this offset from a properly setup pytz "timezone" class. I wrote about how to set it up in the readme under "further application". Hope that helped.

**Comment by communikein** [comment]
That wasn't exactly what I was looking for, but it pointed me in the right direction ;)
In the end this is the function I wrote to get what I wanted (if you consider this post to not be useful, feel free to remove it):

```
from timezonefinder import TimezoneFinder
from pytz import timezone
import pytz
from datetime import datetime

utc = pytz.utc
tf = TimezoneFinder()

def diff_time_zone(target):
	today = datetime.now()

	tz_target = timezone(tf.certain_timezone_at(lat=target['lat'], lng=target['lng']))
	today_target = tz_target.localize(today)
	today_utc = utc.localize(today)

	return (today_utc - today_target).total_seconds() / 60
```
If I pass it a dictionary, like this one
`bergamo = dict({'lat':45.69, 'lng':9.67})`

It returns me the number of minutes the location's time zone is away from the UTC 0

**Comment by MrMinimal64** [comment]
Ok. I'll add this to the readme for further reference.

**Comment by phineas-pta** [comment]
Instead of doing:
```
today_target = tz_target.localize(today)
today_utc = utc.localize(today)
offset = today_utc - today_target
```

we can directly do: `offset = tz_target.utcoffset(today)`

Also, if `today` is in summer time while the `target` isn't, you may want to substract the DST: `offset = tz_target.utcoffset(today) - tz_target.dst(today)`
