### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by MrMinimal64** [MrMinimal64/timezonefinder#56]
- enable and display the test coverage.
- write tests to improve coverage

**Comment by adamchainz** [comment]
FYI you can do this with the `pytest-cov` plugin and these options in setup.cfg:

```
[tool:pytest]
addopts = --cov=timezonefinder
          --cov-report term-missing
          --cov-fail-under 100
```

**Comment by MrMinimal64** [comment]
thx. thats actually what i have tried. Even though all the tests are running they do not seem to contribute to the coverage calculation (i get a coverage of 0%):

```
plugins: cov-2.5.1
collected 14 items                                                                                                                                                      

test/helpers_test.py ...                                                                                                                                          [ 21%]
test/test_functional.py ......                                                                                                                                    [ 64%]
test/test_it.py .....        [100%]C
overage.py warning: No data was collected. (no-data-collected)
[...]
```

I guess my test setup is just a little off at some point, but unfortunatelly at the moment I do not have the time to look into in further (will just upload the new version without coverage support now).
