### ISSUE TITLE
Readme not rendering on PyPI

### ISSUE THREAD

**Issue by pganssle** [MrMinimal64/timezonefinder#58]
The problem is in the `REAME.rst` under [Installation](https://github.com/MrMinimal64/timezonefinder/blob/master/README.rst#installation), there is a broken link (missing space between "feedstock" and the `<`). This is causing `readme_renderer` to choke, which then causes `long_description` to fail to render on PyPI.

You can check the README yourself with:

```python
pip install readme_renderer
python setup.py check -r -s
```

**Comment by MrMinimal64** [comment]
yes, thanks. i already fixed it in the dev branch. is there a way of updating the readme without uploading a new version to pyPi?

**Comment by adamchainz** [comment]
no

**Comment by pganssle** [comment]
I don't think so, but generally this is what a [post release](https://www.python.org/dev/peps/pep-0440/#post-releases) is for.
