### ISSUE TITLE
certain_timezone_at fails for small pocket in Saskatchewan

### ISSUE THREAD

**Issue by JoelBennett** [MrMinimal64/timezonefinder#59]
For some reason certain_timezone_at() fails for a small location in the middle of Saskatchewan on version 2.1.2.  This can be recreated with the following snippet:

```
from timezonefinder import TimezoneFinder
tf = TimezoneFinder()
tf.certain_timezone_at(lat=53.0742, lng=-108.9086) # Returns none.  Should return u'America/Regina'
```

`closest_timezone_at` works for this location, so we were able to fall back to that, but for some reason that particular latitude/longitude fail.  Given that Saskatchewan is basically a giant rectangle, this caught me off guard.  Is this perhaps an issue with the underlying data?  It shouldn't be anywhere near a coastline, so that shouldn't be an issue.

**Comment by MrMinimal64** [comment]
Sorry for taking this long.
First of all (with the current version of timezonefinder) I get 'America/Edmonton' for this point, which is actually correct. Note that timezones do not necessarily follow state borders. You can have a look at this demo here: http://timezonefinder.michelfe.it/gui/0_-108.9086_53.0742 (this is the result of timezonefinderL).
If this is not correct behaviour, you should post this at: https://github.com/evansiroky/timezone-boundary-builder

Hope I could help.

**Comment by JoelBennett** [comment]
No worries!
