### ISSUE TITLE
six dependency missing

### ISSUE THREAD

**Issue by cedbeu** [MrMinimal64/timezonefinder#61]
As mentioned in the [README.rst](https://github.com/MrMinimal64/timezonefinder/blob/dev/README.rst), library `six` is now required but, not set up as a required dependency. It is not resolved automatically when installing `timezonefinder`.

Suggested:
- update requirements in [setup.py](https://github.com/MrMinimal64/timezonefinder/blob/dev/setup.py)
- update comments in [publish.py](https://github.com/MrMinimal64/timezonefinder/blob/dev/publish.py)

**Comment by MrMinimal64** [comment]
Thanks for pointing that out. I am working on it.

**Comment by cedbeu** [comment]
OK, great, thanks!

I wanted to submit a pull request for that, but, long time I didn't use Github and I got some authentication issues.

I don't know much about the process of publishing on pypi… When do you think this new fixed version will be available for deployment through pip/pipenv? Is it a continuous deployment process from github to pypi? (means, almost immediate?)

Also, I see there is a new requirement in 3.0.2 `kwargs_only`, please, make sure to put it everywhere so the dependencies are correctly resolved during installation ;)

Thanks!

I like this project, this is super very useful, even with the 40Mo of data (which is not that much considering the usefulness); I will watch it, and, if I have the opportunity, will be happy to bring my contributions

**Comment by MrMinimal64** [comment]
I just uploaded it. It is available now with pip (pyPI).
Yes, this time I put ``kwargs_only`` in the requirements right away.

Thanks. Feel free to contribute or ask questions.
