### ISSUE TITLE
RuntimeWarning: overflow encountered in long_scalars - trying to figure out why

### ISSUE THREAD

**Issue by JoelBennett** [MrMinimal64/timezonefinder#62]
I'm trying to track down a potential issue (either with my own code base (more likely) or the library (less likely)).  When running unit tests on a Django application that makes use of the timezonefinder library, I'm getting the following warning printed out:

```
C:\Python27\lib\site-packages\timezonefinder\helpers.py:42: RuntimeWarning: overflow encountered in long_scalars
  if (x1GEx and x2GEx) or ((x1GEx or x2GEx) and (y2 - y) * (x2 - x1) >= (y2 - y1) * (x2 - x)):
```

My first thought is that I was somehow passing it bad data, which would seem logical given the warning - if you pass a really large value for y (or x), it could result in an overflow.  That makes sense.  But what doesn't make sense it it seems almost non-deterministic.  If I put a single six.print() statement inside helpers.py, just before that statement, the warning goes away.  I am at a bit of a loss as to why this would change anything.  Is the six library somehow changing precision of something?  Is there any way to tell the timezonefinder library to run using more bits to get around this?

**Comment by MrMinimal64** [comment]
Thanks for pointing this out. I am not sure why the error is not reproducible in some cases, but this is actually secondary since it is enough that you encounter an error in some cases. Can you please post here with which specific input you (sometimes) encounter the error? I thought I had considered this and ruled out any possible overflow (because of dealing with coordinates in a limited range here), but from what you write I think its more likely I made a mistake in my calculation than you misusing the package (too large input values for lng and lat should raise an error).

**Comment by JoelBennett** [comment]
Wow, thanks for the quick response!  I was finally able to replicate it consistently with the following snippet:

```
from timezonefinder import TimezoneFinder
longitude = -123.2
latitude = 48.4
tf = TimezoneFinder()
timezone = tf.certain_timezone_at(lat=float(latitude), lng=float(longitude))
```
In the code base, the longitude and latitude were being parsed from some other location, hence being casted to a float.

**Comment by MrMinimal64** [comment]
That just gets me `America/Vancouver` without any overflow (64bit MacBook). On what kind of system are you running this? Maybe on some architectures the accuracy is actually a problem. Can anyone else verify please?

**Comment by JoelBennett** [comment]
Windows 10, 64 bit.  timezonefinder 3.1.0, Django 1.11, and Python 2.7.14 (64 bit).

Again, it's quite possible we're doing something wrong on our end.

**Comment by JoelBennett** [comment]
Unfortunately upgrading this project to Python 3 right now isn't an option. :( 

So just for kicks, I dropped a print statement in to see what the values of y, y1, y2 and x, x1, x2 were just before it throws the warning.  I was also curious to know what datatypes are being used, so I dumped those out as well.  Using the same snippet as before, this is what I see:

```
>>> from timezonefinder import TimezoneFinder
>>> longitude = -123.2
>>> latitude = 48.4
>>> tf = TimezoneFinder()
>>> timezone = tf.certain_timezone_at(lat=float(latitude), lng=float(longitude))
y2: 484018500 y1: 483983640 y: 484000000 x2: -1250462970 x1: -1250465050 x: -1232000000
y2: <type 'numpy.int32'> y1: <type 'numpy.int32'> y: <type 'int'> x2: <type 'numpy.int32'> x1: <type 'numpy.int32'> x: <type 'int'>
y2: 484228330 y1: 482840280 y: 484000000 x2: -1231151390 x1: -1232484440 x: -1232000000
y2: <type 'numpy.int32'> y1: <type 'numpy.int32'> y: <type 'int'> x2: <type 'numpy.int32'> x1: <type 'numpy.int32'> x: <type 'int'>
C:\Python27\lib\site-packages\timezonefinder\helpers.py:31: RuntimeWarning: overflow encountered in long_scalars
  if (x1GEx and x2GEx) or ((x1GEx or x2GEx) and (y2 - y) * (x2 - x1) <= (y2 - y1) * (x2 - x)):
C:\Python27\lib\site-packages\timezonefinder\helpers.py:41: RuntimeWarning: overflow encountered in long_scalars
  if (x1GEx and x2GEx) or ((x1GEx or x2GEx) and (y2 - y) * (x2 - x1) >= (y2 - y1) * (x2 - x)):
y2: 484321020 y1: 483643940 y: 484000000 x2: -1245040010 x1: -1242579870 x: -1232000000
y2: <type 'numpy.int32'> y1: <type 'numpy.int32'> y: <type 'int'> x2: <type 'numpy.int32'> x1: <type 'numpy.int32'> x: <type 'int'>
```

Given the order of the print statements, I though it would have been the values right before the warning that cause issues (e.g.: `y2: 484228330 y1: 482840280 y: 484000000 x2: -1231151390 x1: -1232484440 x-1232000000`).  I find it curious that the internal types appear to be either int or numpy.int32.  Is this possibly related to the version of numpy I have installed?  If I try the following, I don't seem to get any warnings:

```
>>> y2 = 484228330
>>> y1 = 482840280
>>> y = 484000000
>>> x2 = -1231151390
>>> x1 =  -1232484440
>>> x =  -1232000000
>>> (y2 - y) * (x2 - x1) <= (y2 - y1) * (x2 - x)
True
```

**Comment by MrMinimal64** [comment]
Interesting. Could you please try to catch the overflow warning like an error and only print out the important infos then like:

```
#your code
import warnings
numpy.seterr(all='warn')
warnings.filterwarnings('error')
try:
   timezone = tf.certain_timezone_at(lat=float(latitude), lng=float(longitude))
except Warning:
    print(y2 - y, type(y2 - y))
    print(x2 - x1, type(x2 - x1))
    print((y2 - y) * (x2 - x1), type((y2 - y) * (x2 - x1)))

    print(y2 - y1, type(y2 - y1))
    print(x2 - x, type(x2 - x))
    print((y2 - y1) * (x2 - x), type((y2 - y1) * (x2 - x)))

```
I never did this, but you can check this post:
https://stackoverflow.com/questions/15933741/how-do-i-catch-a-numpy-warning-like-its-an-exception-not-just-for-testing

**Comment by JoelBennett** [comment]
```
>>> from timezonefinder import TimezoneFinder
>>> longitude = -123.2
>>> latitude = 48.4
>>> tf = TimezoneFinder()
>>> timezone = tf.certain_timezone_at(lat=float(latitude), lng=float(longitude))
228330 <type 'numpy.int32'>
1333050 <type 'numpy.int32'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\kwargs_only.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\timezonefinder\timezonefinder.py", line 585, in certain_timezone_at
    if inside_polygon(x, y, self.coords_of(line=polygon_nr)):
  File "C:\Python27\lib\site-packages\timezonefinder\helpers.py", line 41, in inside_polygon
    print((y2 - y) * (x2 - x1), type((y2 - y) * (x2 - x1)))
RuntimeWarning: overflow encountered in long_scalars
```

**Comment by MrMinimal64** [comment]
v3.2.0 should fix your issue. int64 accuracy actually is needed here! Can you please try updating your numpy version first before upgrading timezonefinder and tell me if this also resolves your issue? When I check the data types of `(y2 - y) * (x2 - x1)` it is apparently automatically being converted to `<class 'numpy.int64'>` for me and hence I dont face overflow. Maybe just requiring a newer numpy version instead of forcing the typing to int64 is a better option.

**Comment by JoelBennett** [comment]
Hah!  It did indeed fix it!  For some reason I was thinking that v3.1.0 was the latest version.  It runs nice and clean - no warnings under v.3.2.0.  Thanks for all the help with this!

**Comment by MrMinimal64** [comment]
Up until yesterday 3.1.0 also was the latest version! i created 3.2.0 to fix this issue, so no false alarm at all! If you have time: It would be very helpful for me to know if using the newest numpy version together with the old 3.1.0 timezonefinder also resolves the problem for you. at the moment I artificially enforce int64 types where needed, but it would be nice to avoid this when newer numpy versions automatically take care of it. Do you get my point? Thx

**Comment by JoelBennett** [comment]
On Numpy 1.15.3 (which I think is the latest) and timezonefinder 3.1.0, I still get the original RuntimeWarning.

**Comment by MrMinimal64** [comment]
Ok, then i'll leave the static typing. thanks for checking.

**Comment by JoelBennett** [comment]
Again, thanks for all the help on this!

**Comment by JoelBennett** [comment]
I can't get too much into the business details, but I can say that we are trying to determine the timezone for a given latitude/longitude, and we need it to be somewhat accurate.  I still think on our end that we could use closest_timezone_at(), and if that fails, then try using certain_timezone_at(), but good luck getting management to grant us the time to make that change. :(
