### ISSUE TITLE
Multiple distances to the same timezone

### ISSUE THREAD

**Issue by ravivmg** [MrMinimal64/timezonefinder#67]
When I run closest_timezone_at, I thought that it would return one distance value per timezone. However, when I run it I sometimes get multiple results for one timezone. For example, the following:

`tf.closest_timezone_at(lng=-85.2692, lat=31.6575, delta_degree=8,return_distances=True, force_evaluation=True, exact_computation=True)`

returns two hits for the New York timezone

`('America/New_York',
 array([ 14.21944659, 754.67091603, 749.29385281, 741.37317121,
        704.2011185 , 724.31508828, 699.01969573, 781.7355791 ,
        551.5451686 , 771.86319838,  14.21944659, 791.60531965]),
 ['America/Chicago',
  'America/Indiana/Indianapolis',
  'America/Indiana/Petersburg',
  'America/Indiana/Vincennes',
  'America/Kentucky/Louisville',
  'America/Indiana/Marengo',
  'America/Indiana/Tell_City',
  'America/Indiana/Vevay',
  'America/Kentucky/Monticello',
  'America/Nassau',
  'America/New_York',
  'America/New_York'])`

Is this a bug or a feature?

**Comment by MrMinimal64** [comment]
It is a feature. A single timezone might be represented by multiple polygons and the distance to each of the candidate polygons is being computed and returned.

**Comment by MrMinimal64** [comment]
I am curious what you use the distance to the different timezones for. Have you noted that the timezone polygons currently in use do not follow the geographical shorelines?

**Comment by ravivmg** [comment]
Got it. Thanks. I am an economist, and I have a hypothesis that coworkers that collaborate across timezone borders face a certain coordination cost because of it. I have been able to use your tool to find which individuals in my data are closer versus farther from a timezone boundary. Since I mostly care about the horizontal distance for U.S. timezones, I haven't had a big issue with the shorelines.

**Comment by MrMinimal64** [comment]
Hey, that is a cool application for this package! Glad it is being used in that way. Good luck with your work.
