### ISSUE TITLE
Drop Python2 support

### ISSUE THREAD

**Issue by MrMinimal64** [MrMinimal64/timezonefinder#72]
Just as a heads-up:
As many other projects (cf. https://python3statement.org/) I decided to drop the support for python2 with the next timezonefinder release. This is justified by the past compatibility issues and the increased effort of maintaining the compatibility (more tests, dependencies, code...). 
The new release hence will be "4.0.0".

**Comment by adamchainz** [comment]
+1 I'm doing the same on my projects.
