### ISSUE TITLE
Support for pandas dataframe

### ISSUE THREAD

**Issue by danielsaaf** [MrMinimal64/timezonefinder#76]
Hi. 

One feature that I am missing is the possibility to compute the timezones from a pandas dataframe containing Latitude and Longitude. 
If you think this might be a feature that suites into this package, I can try to implement it.

**Comment by cstich** [comment]
What's wrong with using `DataFrame.apply`? Wouldn't something like `df.apply(lamda row: tf.timezone_at(lng=row.longitude, lat=row.latitude), axis=1)` work?

**Comment by danielsaaf** [comment]
Yes, I found that solution myself after some testing. 
Sorry for being to quick to post.. ;) I like this project and would like to be able to contribute, but will have to look for another opportunity. I will close this issue!

**Comment by anuragblumer** [comment]
@cstich DataFrame.apply would be very slow. A vectorized solution will be more efficient.

**Comment by jannikmi** [comment]
Can you please elaborate why a vectorised function would be more efficient?
