### ISSUE TITLE
Suggestion: vectorizing

### ISSUE THREAD

**Issue by phineas-pta** [MrMinimal64/timezonefinder#82]
Your package is very helpful, thanks a lot :smile:

Just thinking, maybe you can vectorize all the functions so they can be use on a `numpy array` or `pandas DataFrame`, it'll be awesome for those who work with geo data

I know we can use `.apply` but why not vectorize :wink: ?

**Comment by MrMinimal64** [comment]
Thanks for the suggestion.
What prevents you from using numpy.vectorize?
https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html

**Comment by phineas-pta** [comment]
`numpy.vectorize` works but it's essentially a `for` loop, not a "true" vectorizing

**Comment by MrMinimal64** [comment]
What should a "true" vectorized function do differently?

**Comment by phineas-pta** [comment]
I don't know whether it's possible with your code, I'm thinking about using `numpy.array` as the backend directly, and doing all the calculations with `numpy` functions

**Comment by MrMinimal64** [comment]
Maybe I am missing something, but from my point of view this is not possible or at least not beneficial. Each lat, lng coordinate pair represents their own query point and each of those point requires a separate procedure (independent from all others). This package does not really operate on the coordinates of the query points but rather the internal representation of the timezones. numpy functions are hence not useful in the use case you describe.

Please note that even ``numpy`` functions use ``for`` loops (this is not a bad thing) and this package already uses ``numpy`` functions internally to handle the timezone polygons. 

Thanks for the suggestion, but I believe using the existing functions ``DataFrame.apply`` and ``numpy.vectorize`` already covers this use case best.
I am closing this issue now. Feel free to comment if you are having doubts.
