### ISSUE TITLE
Ocean Locations

### ISSUE THREAD

**Issue by ostwalprasad** [MrMinimal64/timezonefinder#84]
Readme says current data set in use: `precompiled timezone-boundary-builder (without oceans).`

All my points are in ocean, Is there any way I can use data with ocean?

I tried several locations in sea. It returns None.

**Comment by MrMinimal64** [comment]
yes, you can build your own version with ocean by downloading the data versions with oceans from https://github.com/evansiroky/timezone-boundary-builder/releases
and then compile the data as described in the readme https://github.com/MrMinimal64/timezonefinder#further-application under "parsing the data"
hope that helped

**Comment by ostwalprasad** [comment]
Thanks Jannik! I was able to build ocean file and get sea timezones!

 It works like a charm!

**Comment by MrMinimal64** [comment]
Great that it worked!
I want to remark that I am not including the oceans in the vanilla timezonefinder version, because:

1. in the most use cases ocean timezones are not relevant
2. sometimes it is important to detect coordinates outside a (land) timezone and that is not possible when a sea timezone polygon is being matched
3. it would increase the size of timezonefinder

**Comment by zedrdave** [comment]
I fully respect the decision (and appreciate the tool!), but I wonder if it's really the best default option:

- Detecting whether coordinates are within country boundary or outside, should probably be handled separately (rules being a bit more complex than timezones)

- Is the size really increased that much? Oceans timezones are fairly simple, compared to country boundaries, aren't they?

**Comment by MrMinimal64** [comment]
> Detecting whether coordinates are within country boundary or outside, should probably be handled separately (rules being a bit more complex than timezones)

Can you please clarify. The current data in use does not follow country boundaries.

The "with oceans-"releases from https://github.com/evansiroky/timezone-boundary-builder/releases have size around 10% larger.

**Comment by zedrdave** [comment]
@MrMinimal64 I was referring to your #2 reason for excluding oceans (unless I misunderstood): the ability to tell whether coords on land or sea, seems like it shouldn't fall on this tool… As long as the timezone is accurate, there are always other tools to figure out whether a mappoint is land, EEZ, international waters etc.

**Comment by MrMinimal64** [comment]
Yes, I see your point now. What I wrote is misleading. This package should not be used for detecting coordinates off land. I should have formulated it in a different way:

2. Sometimes it is important to handle coordinates far off land differently (e.g. to ask a user to confirm coordinates again). When a sea timezone polygon is being matched, that distinction is harder to make.

This is not a very strong point though.
I also have to admit that I currently don't know what sea timezone names look like. Can someone educate me?
