### ISSUE TITLE
timezonefinder vs timezonefinderL

### ISSUE THREAD

**Issue by zedrdave** [MrMinimal64/timezonefinder#85]
I am trying to understand the implications of using one vs the other, and have a few questions:

1. With memory mode = `false`, wouldn't using `timezonefinderL` be equivalent to using `timezonefinder`'s `timezone_at`, in terms of speed and memory load? Since that function supposedly uses only shortcuts, same as `timezonefinderL`.

2. Wouldn't it be possible to provide a "limited" memory mode that only loads shortcuts for `timezonefinder`, to get the best of both world: fast lookups in most cases, and the option to do a deeper lookup when the tz returned is `None`.

**Comment by MrMinimal64** [comment]
1.  `timezonefinder`'s `timezone_at` uses shortcuts. It just avoids checking the main timezone polygons as much as possible. This functions is much more precise, but also slower than `timezonefinderL`’s `timezone_at`.  

2. Please note: `timezonefinder`'s `timezone_at` and `timezonefinderL`’s `timezone_at` both definitely return a timezone when a shortcut is present in that region. There should be no case where one function returns `None` and the other one returns a timezone. You can however first query one of those methods and later call `timezonefinder`'s `closest_timezone_at` when the tz returned is `None`. 

Hope that helped. Please reopen this issue if questions remain.

**Comment by zedrdave** [comment]
I have been looking a bit more at the code for both and understand a bit better now (although not yet fully).

I'm still not sure I see the point in splitting the codebase in two: wouldn't it be simply a matter of having a flag/parameter telling `timezone_at` to give up and return, when there is no shortcuts? Along with a limited `in_memory` mode that only loads non-polygon files, maybe? 

As far as I can tell, with a few conditional blocks, you could merge the two without any serious speed or memory cost (the only difference would be some extra disk space use, but that doesn't seem worth the effort of duplicating the tool), or am I missing something?

**Comment by MrMinimal64** [comment]
Yes, valid objection. Previously `timezonefinderL` had its own data of simplified polygons. This simplification is however not feasible any more with the data base currently in use, so I switched to this implementation. As you correctly identified this makes the two packages very similar. The only advantage of `timezonefinderL` is indeed the disk space (38MB difference).

Thanks for suggesting this feature. I will open up a new issue for this.
May I ask what your use case is in order to understand the needs of the user better.

**Comment by zedrdave** [comment]
Regarding my use case (but I think the above feature would be beneficial to most users regardless of use case): I need TZ data for map points mainly located on sea (used in mapping routes for boats).

In terms of speed/memory/disk use/accuracy trade-off, I would say my ideal workflow (and what I would suggest to implement as a sensible default for the package) would be:

1. Full binary files that include oceans (considering the fairly low disk/RAM gain from excluding them)

2. Shortcut files with perhaps a bit more precision (eg doubled): still a much smaller RAM footprint over the full polygon files, with a much better chance of hitting a shortcut without needing polygons (especially in ocean areas, where timezone areas tend to be much straighter)

3. Only shortcut files are loaded into memory, leading to very fast / low RAM footprint lookups for the majority of points.

4. Polygon files are only used, for the small number of points that can't be resolved through shortcuts (if I got it right, you aren't loading the whole file into memory to do the lookups, but use a file cursor instead, correct?).

**Comment by MrMinimal64** [comment]
thanks for the valuable feedback and suggestions. I'll work on this as soon as possible.

TODO:

- add option to only load shortcuts
- load shortcuts into memory by default, introduction of flag?
- timezonefinder L deprecate
