### ISSUE TITLE
consider including ocean timezones

### ISSUE THREAD

**Issue by MrMinimal64** [MrMinimal64/timezonefinder#88]
- inspect ocean timezone name formatting (output)
- consider drawbacks, size?
- flag to leave out?
- parse separate binary files for ocean timezones?

**Comment by MrMinimal64** [comment]
will be handled like #89 (own package for ocean data)
work in progress

**Comment by MrMinimal64** [comment]
Work on this has been suspended, due to the complications stated in #89.

Since [v4.4.0 ](https://github.com/MrMinimal64/timezonefinder/releases/tag/v4.4.0) however the new shell script ``parse_data.sh`` also supports downloading the latest timezone data with oceans (cf. [documentation](https://timezonefinder.readthedocs.io/en/latest/2_use_cases.html#data-parsing-shell-script)).

Let me know if this functionality is not enough for your usecase.

**Comment by hamiltoncj** [comment]
I would prefer that timzonefinder included the time zones with the ocean by default. I am not sure what the "complication" is, but QGIS is now using timezonefinder, but it is not getting the ocean time zones. As a QGIS plugin developer those data files are too large to include in a plugin so it it better if the QGIS project includes everything. It is more work for them, and they may not do it, to download and compile the time zones with ocean.  Thanks!!!

**Comment by MrMinimal64** [comment]
Ok, thanks for your input! I will reconsider adding the ocean timezones by default.

**Comment by zedrdave** [comment]
@jannikmi Does the merge above, imply that there is no longer a need to manually download and index `combined-with-oceans.json`? Or does the code modification only extend the results returned to cover oceans, without necessarily using the full boundaries file?

**Comment by jannikmi** [comment]
yes, the `combined-with-oceans.json` is being used by default since version [5.0.0](https://github.com/jannikmi/timezonefinder/blob/master/CHANGELOG.rst#500-2020-12-23).
Use the regular [`Timezonefinder.timezone_at(...)`](https://timezonefinder.readthedocs.io/en/latest/4_api.html#timezonefinder.TimezoneFinder.timezone_at) in order to also retrieve ocean timezones.

> Or does the code modification only extend the results returned to cover oceans, without necessarily using the full boundaries file?

I don't understand how that would work. Can you please clarify?

**Comment by zedrdave** [comment]
> I don't understand how that would work. Can you please clarify?

Nevermind. 😅 The way TZ works is no longer very fresh in my mind, and I was unsure if there was any way that the modification might not extend to full oceans boundaries. Clearly it does.
Thanks again for your work!
