### ISSUE TITLE
load binary files on demand

### ISSUE THREAD

**Issue by MrMinimal64** [MrMinimal64/timezonefinder#89]
find best technical solution
consider drawback of having the user use the package (with internet connection) first before being able to access data. no "offline" lookup package during the first usage.

**Comment by MrMinimal64** [comment]
found solution to create a separate package with just the data. 
easy installation by specifying an "extra" (defined in setup.py).
work in progress

**Comment by MrMinimal64** [comment]
Problem: separate (redundant) tests (for data and code) required, but tests depend on both data and code at the same time!

**Comment by MrMinimal64** [comment]
Due to the problems stated above, the work on splitting up the code from the data into separate packages has been suspended. Please let me know if there those complications can be circumvented.

Since [v4.4.0 ](https://github.com/MrMinimal64/timezonefinder/releases/tag/v4.4.0) however with the class ``TimezoneFinderL`` only shortcuts can be used (without the timezone polygon data). The binary files can be deleted if necessary (cf. [documentation](https://timezonefinder.readthedocs.io/en/latest/1_usage.html#timezonefinderl)).

Let me know if this functionality is not enough for your usecase.

**Comment by apiszcz** [comment]
Thank you for parse script and ocean support, executed per documentation and now I have ocean coverage.

**Comment by MrMinimal64** [comment]
glad i could help!
